apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: elasticsearch-agent-sample
spec:
  components:
    - type: elasticsearch-agent
      name: elasticsearch-agent
      properties:
        version: 8.6.2
        elasticsearchRefs:
          - name: elasticsearch-cluster
        daemonSet:
          podTemplate:
            spec:
              securityContext:
                runAsUser: 0
        config:
          inputs:
            - name: system-1
              revision: 1
              type: system/metrics
              use_output: default
              meta:
                package:
                  name: system
                  version: 0.9.1
              data_stream:
                namespace: default
              streams:
                - id: system/metrics-system.cpu
                  data_stream:
                    dataset: system.cpu
                    type: metrics
                  metricsets:
                    - cpu
                  cpu.metrics:
                    - percentages
                    - normalized_percentages
                  period: 10s
