apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: elasticsearch-enterprise-search-sample
spec:
  components:
    - type: elasticsearch-enterprise-search
      name: elasticsearch-enterprise-search
      properties:
        version: 8.6.2
        count: 1
        elasticsearchRef:
          name: elasticsearch-cluster
