apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: elasticsearch-cluster-sample-with-agent-as-trait
spec:
  components:
    - type: elasticsearch-cluster
      name: elasticsearch-cluster
      properties:
        version: 8.6.2
        nodeSets:
          - name: default
            count: 1
            podTemplate:
              spec:
                containers:
                  - name: elasticsearch
                    resources:
                      requests:
                        memory: 1Gi
                        cpu: 1
                      limits:
                        memory: 1Gi
                        cpu: 1
            config:
              node.store.allow_mmap: false
      traits:
        - type: elasticsearch-agent
          properties:
            version: 8.6.2
            elasticsearchRefs:
              - name: elasticsearch-cluster
            daemonSet:
              podTemplate:
                spec:
                  securityContext:
                    runAsUser: 0
            config:
              inputs:
                - name: system-1
                  revision: 1
                  type: system/metrics
                  use_output: default
                  meta:
                    package:
                      name: system
                      version: 0.9.1
                  data_stream:
                    namespace: prod
                  streams:
                    - id: system/metrics-system.cpu
                      data_stream:
                        dataset: system.cpu
                        type: metrics
                      metricsets:
                        - cpu
                      cpu.metrics:
                        - percentages
                        - normalized_percentages
                      period: 10s
