apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nacos-cluster-sample
spec:
  components:
    - type: nacos-cluster
      name: nacos-cluster
      properties:
        type: standalone
        image: nacos/nacos-server:1.4.1
        replicas: 1
