apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: otel-instrumentation-sample
spec:
  components:
    - type: "k8s-objects"
      name: "otel-deploy"
      properties:
        objects:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: my-app
              labels:
                app: my-app
            spec:
              selector:
                matchLabels:
                  app: my-app
              replicas: 1
              template:
                metadata:
                  labels:
                    app: my-app
                  annotations:
                    instrumentation.opentelemetry.io/inject-java: "true"
                spec:
                  containers:
                    - name: myapp
                      image: jaegertracing/vertx-create-span:operator-e2e-tests
                      ports:
                        - containerPort: 8080
                          protocol: TCP
      traits:
        - type: opentelemetry-instrumentation
          properties:
            exporter:
            # endpoint: ""      // Collector endpoint url here, if configured collector is availble.
            propagators:
              - tracecontext
              - baggage
            sampler:
              type: parentbased_traceidratio
              argument: "1"
