apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: volcano-job-sample
spec:
  components:
    - type: volcano-job
      name: volcano-job-sample
      properties:
        minAvailable: 1
        policies:
          - action: RestartJob
            event: PodEvicted
        queue: default
        schedulerName: volcano
        tasks:
          - name: nginx
            policies:
              - action: CompleteJob
                event: TaskCompleted
            replicas: 1
            template:
              spec:
                containers:
                  - command:
                      - sleep
                      - 10m
                    image: nginx:latest
                    name: nginx
                    resources:
                      limits:
                        cpu: 1
                      requests:
                        cpu: 1
