apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kafka-user-sample
spec:
  components:
    - type: kafka-user
      name: kafka-user
      properties:
        authentication:
          type: tls
        authorization:
          type: simple
          acls:
            - resource:
                type: topic
                name: kafka-topic
                patternType: literal
              operations:
                - Read
              host: '*'
            - resource:
                type: topic
                name: kafka-topic
                patternType: literal
              operations:
                - Describe
              host: '*'
            - resource:
                type: topic
                name: kafka-topic
                patternType: literal
              operations:
                - Write
              host: '*'
            - resource:
                type: topic
                name: kafka-topic
                patternType: literal
              operations:
                - Create
              host: '*'
