apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: colocation-profile-sample
spec:
  components:
    - type: "koordinator-colocation-profile"
      name: "koordinator-colocation-profile"
      properties:
        namespaceSelector:
            matchLabels:
            koordinator.sh/enable-colocation: "true"
        selector:
            matchLabels:
            koordinator.sh/enable-colocation: "true"
        qosClass: BE
        priorityClassName: koord-batch
        koordinatorPriority: 1000
        schedulerName: koord-scheduler
        labels:
            koordinator.sh/mutated: "true"
        annotations:
            koordinator.sh/intercepted: "true"
        patch:
            spec:
                terminationGracePeriodSeconds: 30
